# CE-40717: Machine Learning

## Hands-On Workshop - Second Session

### Python for Data Analysis-NumPy
NumPy is a Linear Algebra Library for Python. The reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks. NumPy is also incredibly fast, as it has bindings to C libraries. NumPy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of NumPy.
<br><br/>
This part of the notebook will just go through the basic topics in order:
>- [Arrays](#Arrays)
>    - [Creation](#Creation)
>    - [Shape Manipulation](#Shape-Manipulation)
>    - [View <span style="color:red">vs</span> Copy](#View-vs-Copy)
>    - [Save & Load](#Save-&-Load)
>- [Indexing & Slicing](#Indexing-&-Slicing)
>- [Basic Array Operations](#Basic-Array-Operations)
>- [Broadcasting](#Broadcasting)
>- [Universal Array Functions](#Universal-Array-Functions)
>- [More Useful Array Operations](#More-Useful-Array-Operations)
<br><br/>
>- <code>***Exercise***</code>

In [1]:
# Importing numpy module into our notebook
import numpy as np

#### Arrays
NumPy arrays are the main way we will use NumPy throughout the course. NumPy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1d arrays and matrices are 2d (note that a matrix can still have only one row or one column). Let's begin our introduction by exploring how to create NumPy arrays.

##### Creation

In [2]:
lst = [1, -1, 7]
lst

[1, -1, 7]

In [3]:
arr = np.array(object=lst)
arr

array([ 1, -1,  7])

In [4]:
print(type(arr))
print(arr.dtype)    # tuple, arry shape
print(arr.ndim)     # int, number of array dimension
print(arr.shape)    # Data-type of the array's elements
print(arr.size)     # Number of elements in the array

<class 'numpy.ndarray'>
int32
1
(3,)
3


In [5]:
arr = np.array(object=lst, dtype=np.float16)
arr

array([ 1., -1.,  7.], dtype=float16)

In [6]:
print(arr.dtype)

float16


In [7]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
mat = np.matrix(data=matrix)
mat

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [9]:
print(type(mat))
print(mat.dtype)
print(mat.ndim)
print(mat.shape)
print(mat.size)

<class 'numpy.matrix'>
int32
2
(3, 3)
9


In [10]:
mat = np.array(object=matrix)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
print(type(mat))
print(mat.dtype)
print(mat.ndim)
print(mat.shape)
print(mat.size)

<class 'numpy.ndarray'>
int32
2
(3, 3)
9


In [12]:
np.zeros(shape=(2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones(shape=(3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
np.eye(N=4, k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [15]:
np.arange(start=2, stop=11, step=3)

array([2, 5, 8])

In [16]:
np.linspace(start=1, stop=13, num=9)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. , 11.5, 13. ])

In [17]:
np.random.rand(2,3)

array([[0.91880107, 0.60264886, 0.33873721],
       [0.6511602 , 0.98557609, 0.00636224]])

In [18]:
np.random.randn(2,3)

array([[ 0.59441158, -1.84746148, -0.2173215 ],
       [-0.91392213,  0.01494827, -0.74258223]])

In [19]:
np.random.randint(low=-1, high=7, size=(3,4))

array([[ 0,  0,  2,  0],
       [ 3,  3,  3, -1],
       [ 6,  2,  0,  2]])

###### Other methods of array creation:
- np.full
- np.empty
- np.empty_like
- np.zeros_like
- ...

##### Shape Manipulation

In [20]:
mat = np.array(([[ 1, 2, 3],
                 [ 4, 5, 6],
                 [ 7, 8, 9],
                 [10,11,12],
                 [13,14,15]]))
mat

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [21]:
mat.T

array([[ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14],
       [ 3,  6,  9, 12, 15]])

In [22]:
mat.transpose([0,1])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [23]:
mat.transpose([1,0])

array([[ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14],
       [ 3,  6,  9, 12, 15]])

In [24]:
mat.transpose()

array([[ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14],
       [ 3,  6,  9, 12, 15]])

In [25]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [26]:
arr.reshape(1,4)

array([[1, 2, 3, 4]])

In [27]:
arr.reshape(1,4).shape

(1, 4)

In [28]:
arr.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [29]:
arr.reshape(2,2, order='F')    # F means to read/write the elements using Fortran-like index order

array([[1, 3],
       [2, 4]])

##### View <span style="color:red">vs</span> Copy

In [30]:
# Data is not copied, it's a view of the original array! This avoids memory problems!
a = np.arange(start=-3, stop=7)
b = a    # b = a.view()
a

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [31]:
b

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [32]:
b[3] = 7
b

array([-3, -2, -1,  7,  1,  2,  3,  4,  5,  6])

In [33]:
# Note that the changes also occur in the original array!
a

array([-3, -2, -1,  7,  1,  2,  3,  4,  5,  6])

###### <span style="color:orange">*To get a copy, need to be explicit*</span>

In [34]:
a = np.arange(start=-3, stop=7)
b = a.copy()    # b = a.view()
a

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [35]:
b

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [36]:
b[3] = 7
b

array([-3, -2, -1,  7,  1,  2,  3,  4,  5,  6])

In [37]:
a

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

##### Save & Load

In [38]:
arr1 = np.arange(start=-131, stop=131, step=13).reshape(3,7, order='F')
arr1

array([[-131,  -92,  -53,  -14,   25,   64,  103],
       [-118,  -79,  -40,   -1,   38,   77,  116],
       [-105,  -66,  -27,   12,   51,   90,  129]])

In [39]:
np.save(file="./arr1", arr=arr1)

In [40]:
np.load(file="./arr1.npy")

array([[-131,  -92,  -53,  -14,   25,   64,  103],
       [-118,  -79,  -40,   -1,   38,   77,  116],
       [-105,  -66,  -27,   12,   51,   90,  129]])

In [41]:
arr2 = np.linspace(start=-7, stop=7, num=29)
arr2

array([-7. , -6.5, -6. , -5.5, -5. , -4.5, -4. , -3.5, -3. , -2.5, -2. ,
       -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,
        4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ])

In [42]:
# Save dictionary of arrays
np.savez(file="./mul-arr", matrix=arr1, array=arr2)

In [43]:
np.load(file="./mul-arr.npz")

In [44]:
# Load the dictionary of arrays
dic = np.load(file="./mul-arr.npz")
dic["array"]

array([-7. , -6.5, -6. , -5.5, -5. , -4.5, -4. , -3.5, -3. , -2.5, -2. ,
       -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,
        4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ])

In [45]:
dic["matrix"]

array([[-131,  -92,  -53,  -14,   25,   64,  103],
       [-118,  -79,  -40,   -1,   38,   77,  116],
       [-105,  -66,  -27,   12,   51,   90,  129]])

#### Indexing & Slicing
In this part we will discuss how to select elements or groups of elements from an array

<img src="./images/np-indexing&slicing.png" width=737>

In [46]:
arr1d = np.arange(start=2, stop=29, step=3)
arr1d

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26])

In [47]:
arr1d[5]

17

In [48]:
arr1d[-2]

23

In [49]:
arr1d[0:4]

array([ 2,  5,  8, 11])

In [50]:
arr1d[1:4]

array([ 5,  8, 11])

In [51]:
arr1d[3:-2]

array([11, 14, 17, 20])

In [52]:
arr1d[1:4] = -1
arr1d

array([ 2, -1, -1, -1, 14, 17, 20, 23, 26])

In [53]:
arr2d = np.arange(start=1, stop=62, step=4).reshape(4,4)
arr2d

array([[ 1,  5,  9, 13],
       [17, 21, 25, 29],
       [33, 37, 41, 45],
       [49, 53, 57, 61]])

In [54]:
arr2d[1]

array([17, 21, 25, 29])

In [55]:
arr2d[1,:]

array([17, 21, 25, 29])

In [56]:
arr2d[:,1]

array([ 5, 21, 37, 53])

In [57]:
arr2d[1][0]

17

In [58]:
arr2d[1,0]

17

In [59]:
arr2d[1:3,2:]

array([[25, 29],
       [41, 45]])

In [60]:
arr3 = np.empty(shape=(10,10))
arr3

array([[ 1.24002374e+180,  2.46454856e-154,  2.47379808e-091,
         1.18600496e-259,  6.01347002e-154,  6.01346953e-154,
         8.11028038e+016,  5.39948460e-313,  3.27589975e-307,
         1.33360327e+241],
       [ 5.45649998e-310,  3.40605789e-309,  6.95982737e+194,
         8.16552317e-085,  4.73596441e+170,  9.88131292e-324,
         4.24399158e-314,  1.42173718e-312,  5.88999333e+250,
        -1.06827364e-149],
       [ 7.13441583e+091,  5.98233490e-154,  1.17518756e+180,
         7.13836018e+252,  4.96013849e+180,  1.71897984e+161,
         2.18174380e+243,  9.18887581e+170,  4.82406557e+228,
         6.01347002e-154],
       [ 3.81187276e+180,  1.27990068e-152,  2.26723914e+161,
         9.13601355e+242,  3.55455412e+180,  8.87828675e+252,
         1.93975402e+227,  3.67886175e+228,  2.42766848e-154,
         2.62785629e+092],
       [ 2.04553272e-258,  6.01347002e-154,  4.47593816e-091,
         6.01347002e-154,  6.01334635e-154,  1.59704334e+241,
         1.38226806e-310

In [61]:
for i in range(arr3.shape[0]):
    arr3[:,i] = i
arr3

array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [62]:
arr3[:5,[1,7,4,1]]

array([[1., 7., 4., 1.],
       [1., 7., 4., 1.],
       [1., 7., 4., 1.],
       [1., 7., 4., 1.],
       [1., 7., 4., 1.]])

In [63]:
arr4 = np.random.randint(low=-7, high=7, size=(7,7))
arr4

array([[-2,  2, -3,  1, -3, -1,  2],
       [-1,  1,  1, -6, -7,  4, -2],
       [-4, -1,  1,  4, -3,  3,  3],
       [ 3, -2, -2,  0,  1,  5, -1],
       [ 0,  0, -1,  1, -6,  5,  0],
       [ 5,  0, -1,  0,  2, -4, -3],
       [ 2,  6,  4,  0,  5, -2, -5]])

In [64]:
arr4 < 3

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True],
       [ True,  True,  True, False,  True, False, False],
       [False,  True,  True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True, False,  True],
       [False,  True,  True,  True,  True,  True,  True],
       [ True, False, False,  True, False,  True,  True]])

In [65]:
arr4[arr4 < 3]

array([-2,  2, -3,  1, -3, -1,  2, -1,  1,  1, -6, -7, -2, -4, -1,  1, -3,
       -2, -2,  0,  1, -1,  0,  0, -1,  1, -6,  0,  0, -1,  0,  2, -4, -3,
        2,  0, -2, -5])

#### Basic Array Operations

<img src="./images/np-data,ones.png" width=737>

In [66]:
data = np.array([1,2])
ones = np.ones(2, dtype=np.int16)
print(f"data:\t{data}\nones:\t{ones}")

data:	[1 2]
ones:	[1 1]


<img src="./images/np-data+ones.png" width=737>

In [67]:
# print(f"data+ones is: {np.add(data, ones)}")    # Overloaded operators
print(f"data+ones is: {data+ones}")

data+ones is: [2 3]


<img src="./images/np-sub_mult_divide.png" width=737>

In [68]:
# print(f"data-ones is: {np.subtract(data, ones)}\ndata*data is: {np.multiply(data, data)}\ndata/data is: {np.divide(data, data)}\n")    # Overloaded operators
# print(f"data-ones is: {data-ones}\ndata*data is: {data*data}\ndata/data is: {data/data}\n")    # Overloaded operators
print(f"data-ones is: {data-ones}\ndata*data is: {data**2}\ndata/data is: {data/data}")

data-ones is: [0 1]
data*data is: [1 4]
data/data is: [1. 1.]


In [69]:
data = np.arange(1,7).reshape(3,2)
data

array([[1, 2],
       [3, 4],
       [5, 6]])

<img src="./images/np-matrix_aggregation.png" width=737>

In [70]:
print(f"data.max:{data.max():3d}\n\ndata.min:{data.min():3d}\n\ndata.sum:{data.sum():3d}")

data.max:  6

data.min:  1

data.sum: 21


In [71]:
data = np.array([[1,2],
                 [5,3],
                 [4,6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

<img src="./images/np-matrix_aggregation_row.png" width=737>

In [72]:
print(f"\
max.r_wise:\t{data.max(axis=1)}\nargmax.r_wise:\t{data.argmax(axis=1)}\n\
max.c_wise:\t{data.max(axis=0)}\nargmax.c_wise:\t{data.argmax(axis=0)}\n\n\
min.r_wise:\t{data.min(axis=1)}\nargmin.r_wise:\t{data.argmin(axis=1)}\n\
min.c_wise:\t{data.min(axis=0)}\nargmin.c_wise:\t{data.argmin(axis=0)}\n\n\
sum.r_wise:\t{data.sum(axis=1)}\nsum.c_wise:\t{data.sum(axis=0, keepdims=True)}")

max.r_wise:	[2 5 6]
argmax.r_wise:	[1 0 1]
max.c_wise:	[5 6]
argmax.c_wise:	[1 2]

min.r_wise:	[1 3 4]
argmin.r_wise:	[0 1 0]
min.c_wise:	[1 2]
argmin.c_wise:	[0 0]

sum.r_wise:	[ 3  8 10]
sum.c_wise:	[[10 11]]


#### Broadcasting

In [73]:
data = np.array([1,2], dtype=np.float16)
data

array([1., 2.], dtype=float16)

<img src="./images/np-multiply_broadcasting.png" width=737>

In [74]:
data * 1.6

array([1.6, 3.2], dtype=float16)

In [75]:
data = np.arange(1,7).reshape(3,2)
data

array([[1, 2],
       [3, 4],
       [5, 6]])

<img src="./images/np-matrix_broadcasting.png" width=737>

In [76]:
data + np.ones(2)

array([[2., 3.],
       [4., 5.],
       [6., 7.]])

#### Universal Array Functions
NumPy comes with many [Universal Functions (ufunc)](https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [77]:
arr2d = np.random.randint(low=-6, high=6, size=(7,4))
arr2d

array([[-5,  2,  2,  4],
       [ 1,  0, -3,  0],
       [-5, -3,  0, -4],
       [ 0,  0, -3,  1],
       [ 2, -4,  4, -4],
       [-4, -6, -2, -4],
       [-4,  3,  1,  1]])

In [78]:
np.sign(arr2d)

array([[-1,  1,  1,  1],
       [ 1,  0, -1,  0],
       [-1, -1,  0, -1],
       [ 0,  0, -1,  1],
       [ 1, -1,  1, -1],
       [-1, -1, -1, -1],
       [-1,  1,  1,  1]])

In [79]:
np.exp(arr2d)

array([[6.73794700e-03, 7.38905610e+00, 7.38905610e+00, 5.45981500e+01],
       [2.71828183e+00, 1.00000000e+00, 4.97870684e-02, 1.00000000e+00],
       [6.73794700e-03, 4.97870684e-02, 1.00000000e+00, 1.83156389e-02],
       [1.00000000e+00, 1.00000000e+00, 4.97870684e-02, 2.71828183e+00],
       [7.38905610e+00, 1.83156389e-02, 5.45981500e+01, 1.83156389e-02],
       [1.83156389e-02, 2.47875218e-03, 1.35335283e-01, 1.83156389e-02],
       [1.83156389e-02, 2.00855369e+01, 2.71828183e+00, 2.71828183e+00]])

In [80]:
np.log(arr2d)

<ipython-input-80-c9d75bbbe1fc>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr2d)
<ipython-input-80-c9d75bbbe1fc>:1: RuntimeWarning: invalid value encountered in log
  np.log(arr2d)


array([[       nan, 0.69314718, 0.69314718, 1.38629436],
       [0.        ,       -inf,        nan,       -inf],
       [       nan,        nan,       -inf,        nan],
       [      -inf,       -inf,        nan, 0.        ],
       [0.69314718,        nan, 1.38629436,        nan],
       [       nan,        nan,        nan,        nan],
       [       nan, 1.09861229, 0.        , 0.        ]])

In [81]:
np.cbrt(arr2d)

array([[-1.70997595,  1.25992105,  1.25992105,  1.58740105],
       [ 1.        ,  0.        , -1.44224957,  0.        ],
       [-1.70997595, -1.44224957,  0.        , -1.58740105],
       [ 0.        ,  0.        , -1.44224957,  1.        ],
       [ 1.25992105, -1.58740105,  1.58740105, -1.58740105],
       [-1.58740105, -1.81712059, -1.25992105, -1.58740105],
       [-1.58740105,  1.44224957,  1.        ,  1.        ]])

In [82]:
np.sin(arr2d)

array([[ 0.95892427,  0.90929743,  0.90929743, -0.7568025 ],
       [ 0.84147098,  0.        , -0.14112001,  0.        ],
       [ 0.95892427, -0.14112001,  0.        ,  0.7568025 ],
       [ 0.        ,  0.        , -0.14112001,  0.84147098],
       [ 0.90929743,  0.7568025 , -0.7568025 ,  0.7568025 ],
       [ 0.7568025 ,  0.2794155 , -0.90929743,  0.7568025 ],
       [ 0.7568025 ,  0.14112001,  0.84147098,  0.84147098]])

In [83]:
np.tanh(arr2d)

array([[-0.9999092 ,  0.96402758,  0.96402758,  0.9993293 ],
       [ 0.76159416,  0.        , -0.99505475,  0.        ],
       [-0.9999092 , -0.99505475,  0.        , -0.9993293 ],
       [ 0.        ,  0.        , -0.99505475,  0.76159416],
       [ 0.96402758, -0.9993293 ,  0.9993293 , -0.9993293 ],
       [-0.9993293 , -0.99998771, -0.96402758, -0.9993293 ],
       [-0.9993293 ,  0.99505475,  0.76159416,  0.76159416]])

In [84]:
np.minimum(arr2d, 0)

array([[-5,  0,  0,  0],
       [ 0,  0, -3,  0],
       [-5, -3,  0, -4],
       [ 0,  0, -3,  0],
       [ 0, -4,  0, -4],
       [-4, -6, -2, -4],
       [-4,  0,  0,  0]])

In [85]:
np.maximum(arr2d, 0)

array([[0, 2, 2, 4],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 1],
       [2, 0, 4, 0],
       [0, 0, 0, 0],
       [0, 3, 1, 1]])

In [86]:
np.clip(a=arr2d, a_min=-3, a_max=3)

array([[-3,  2,  2,  3],
       [ 1,  0, -3,  0],
       [-3, -3,  0, -3],
       [ 0,  0, -3,  1],
       [ 2, -3,  3, -3],
       [-3, -3, -2, -3],
       [-3,  3,  1,  1]])

In [87]:
np.where(arr2d%2==0, arr2d, 8)

array([[ 8,  2,  2,  4],
       [ 8,  0,  8,  0],
       [ 8,  8,  0, -4],
       [ 0,  0,  8,  8],
       [ 2, -4,  4, -4],
       [-4, -6, -2, -4],
       [-4,  8,  8,  8]])

In [88]:
np.where(arr2d%2==0, arr2d, arr2d+1)

array([[-4,  2,  2,  4],
       [ 2,  0, -2,  0],
       [-4, -2,  0, -4],
       [ 0,  0, -2,  2],
       [ 2, -4,  4, -4],
       [-4, -6, -2, -4],
       [-4,  4,  2,  2]])

#### More Useful Array Operations

In [89]:
# Converting an ndarray to a list
arr_1 = np.arange(5)
arr_2 = arr_1.tolist()
print("\n", type(arr_1), "\t", arr_1, "\n\n", type(arr_2), "\t\t", arr_2)


 <class 'numpy.ndarray'> 	 [0 1 2 3 4] 

 <class 'list'> 		 [0, 1, 2, 3, 4]


In [90]:
# Type Casting
arr_3 = np.array([-3.7, 14.2, 9.5, -6.3, 8])
arr_4 = arr_3.astype(np.int32)
print("\n", arr_3.dtype, "\t", arr_3, "\n\n", arr_4.dtype, "\t\t", arr_4)


 float64 	 [-3.7 14.2  9.5 -6.3  8. ] 

 int32 		 [-3 14  9 -6  8]


In [91]:
# Sort
arr_5 = np.sort(a=arr_4)
print("\n", arr_5, "\n\n", arr_4)


 [-6 -3  8  9 14] 

 [-3 14  9 -6  8]


In [92]:
# In-Place Sort
arr_4.sort()
print(arr_4)

[-6 -3  8  9 14]


In [93]:
# Concatenation
arr_6 = np.random.randint(low=-3, high=3, size=(3,1,5))
arr_7 = np.random.randint(low=-3, high=3, size=(3,7,5))
arr_8 = np.random.randint(low=-3, high=3, size=(3,2,5))

arr_cat = np.concatenate((arr_6, arr_7, arr_8), axis=1)
print(arr_cat.shape)

(3, 10, 5)


In [94]:
# Stacking
arr_11 = np.random.randint(low=-3, high=3, size=(2,5,8))
arr_12 = np.random.randint(low=-3, high=3, size=(2,5,8))
arr_13 = np.random.randint(low=-3, high=3, size=(2,5,8))

arr_stack0 = np.stack(arrays=(arr_11, arr_12, arr_13), axis=0)
arr_stack1 = np.stack(arrays=(arr_11, arr_12, arr_13), axis=1)
arr_stack2 = np.stack(arrays=(arr_11, arr_12, arr_13), axis=2)
arr_stack3 = np.stack(arrays=(arr_11, arr_12, arr_13), axis=3)

print("\n", arr_stack0.shape,
      "\n", arr_stack1.shape,
      "\n", arr_stack2.shape,
      "\n", arr_stack3.shape)


 (3, 2, 5, 8) 
 (2, 3, 5, 8) 
 (2, 5, 3, 8) 
 (2, 5, 8, 3)


In [95]:
# Matrix Multiplication
arr_14 = np.random.randint(low=-3, high=3, size=(3,5))
arr_15 = np.random.randint(low=-3, high=3, size=(5,7))
# arr_16 = np.matmul(arr_14, arr_15)
arr_16 = arr_14 @ arr_15    # Overloaded operators

print("\n", arr_16.shape)


 (3, 7)


#### <code>***Exercise***</code>
This is an optional exercise to test your understanding of NumPy basics. If you find this extremely challenging, then you probably are not ready for the rest of this course yet and don't have enough experience to continue. We would suggest you keep trying to do some more examples, such as [NumPy: the absolute basics for beginners](https://numpy.org/doc/stable/user/absolute_beginners.html).
<br><br/>
Answer the questions or complete the tasks outlined in bold below, use the specific method described if applicable.

##### Q1:
> <code>**Create an array of 7 fours.**</code>

array([4., 4., 4., 4., 4., 4., 4.])

##### Q2:
> <code>**Create an array of all the even integers from 4 to 40.**</code>

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36,
       38, 40])

##### Q3:
> <code>**Use NumPy to generate a </code>$7\times3$<code> matrix of random numbers sampled from </code>$\mathcal N(\mu=2,\sigma=5)$.**

array([[ 5.14762745,  2.93431957,  6.66186193],
       [ 0.40133075, -5.16125961, -3.90157082],
       [ 0.87206842, -1.73738439, -3.29330845],
       [ 2.12178384,  1.46380784, -1.5928164 ],
       [ 1.82976731,  2.60369603,  2.14766515],
       [-2.0839119 ,  1.1754447 ,  3.06162346],
       [ 4.55748773,  7.90023513, -6.96325582]])

##### Q4:
> <code>**Create the following matrix:**</code>

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

##### Q5:
> <code>**Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:**</code>

In [100]:
arr2d = np.arange(1,26).reshape(5,5)
arr2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [101]:
# Write code here that reproduces the output of the cell
arr2d[...

20

In [102]:
# Write code here that reproduces the output of the cell
arr2d[...

array([21, 22, 23, 24, 25])

In [103]:
# Write code here that reproduces the output of the cell
arr2d[...

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [104]:
# Write code here that reproduces the output of the cell
arr2d[...

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [105]:
# Write code here that reproduces the output of the cell
arr2d[...

array([[ 2],
       [ 7],
       [12]])

##### Q6:
> <code>**Get the row wise standard deviation of elements of the following matrix.**</code>

In [106]:
arr2d = np.arange(start=-32,stop=32).reshape(8,8)
arr2d

array([[-32, -31, -30, -29, -28, -27, -26, -25],
       [-24, -23, -22, -21, -20, -19, -18, -17],
       [-16, -15, -14, -13, -12, -11, -10,  -9],
       [ -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1],
       [  0,   1,   2,   3,   4,   5,   6,   7],
       [  8,   9,  10,  11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29,  30,  31]])

array([[2.29128785],
       [2.29128785],
       [2.29128785],
       [2.29128785],
       [2.29128785],
       [2.29128785],
       [2.29128785],
       [2.29128785]])